### ISSUE TITLE
[Feature Request] Support for Sendy

### ISSUE THREAD

**Issue by marco-martinenghi** [burggraf/supabase-mailer#1]
Hello can you add support for Sendy? https://sendy.co/
Thank you in advance!

**Comment by burggraf** [comment]
Thanks for the suggestion!  I'll take a look at this one.

**Comment by marco-martinenghi** [comment]
Thanks to you! :)

**Comment by burggraf** [comment]
I hit them (Sendy) up asking for a copy for development purposes.  Looks cool.

**Comment by marco-martinenghi** [comment]
Yes, Not very popular, but very affordable with cool features! Keep in touch soon! Thanks for your work!
