### ISSUE TITLE
Error when triggering send_email_message function from client (ReactJS)

### ISSUE THREAD

**Issue by finlaydegrauwe** [burggraf/supabase-mailer#3]
Hi! I'm quite new to Supabase but I'm enjoying it so far. While trying to implement your supabase-mailer with Sendinblue everything runs fine as a query. Once I try to rpc the function to fire it from the client browser (it took me a while to figure out how 😄) I stumble upon the following error:
```
hint: "If a new function was created in the database with this name and parameters, try reloading the schema cache."
message: "Could not find the public.send_email_message(html_body, recipient, sender, subject) function or the public.send_email_message function with a single unnamed json or jsonb parameter in the schema cache"
```
The problem seems to be quite similar to this issue: https://github.com/supabase/pg_graphql/issues/20. I tried to reload the schema cache but that didn't help.

My code for firing the rpc looks like this
```
let { data, error } = await supabase.rpc("send_email_message", {
      sender: "*******@*******.com", //hidden on Github
      recipient: "*******@*******.com", //hidden on Github
      subject: "This is a test message from my Supabase app!",
      html_body:
        '<html><body>This message was sent from <a href="https://postgresql.org">PostgreSQL</a> using <a href="https://supabase.io">Supabase</a> and <a href="https://sendinblue.com">Sendinblue</a>.</body></html>',
    });
```
I think it has something to do with the following lines, making my function public as stated in the send_email_message function but I can't wrap my head around it.
```
-- Do not allow this function to be called by public users (or called at all from the client)
REVOKE EXECUTE on function public.send_email_message FROM PUBLIC;

-- To allow, say, authenticated users to call this function, you would use:
 GRANT EXECUTE ON FUNCTION public.send_email_message TO authenticated;
```
Any help would be greatly appreciated!

**Comment by burggraf** [comment]
Those `REVOKE` and `GRANT` lines are saying "only allow people who are logged in to send messages".  Are you sure you are logged into your app when you try to call the function that sends the message?

**Comment by finlaydegrauwe** [comment]
Thanks for your quick response, and a happy new year to you if you're celebrating!
As far as I know I'm logged in through the supabase auth provider. Although I've only tried through a locally hosted version of the web app, if that could make any difference?

**Comment by finlaydegrauwe** [comment]
I finally solved part of the problem by calling my function through rpc the right way (I wasn't passing my argument the right way): 
```
let { data, error } = await supabase.rpc("send_email_message", { message: {
      sender: "*******@*******.com", //hidden on Github
      recipient: "*******@*******.com", //hidden on Github
      subject: "This is a test message from my Supabase app!",
      html_body:
        '<html><body>This message was sent from <a href="https://postgresql.org">PostgreSQL</a> using <a href="https://supabase.io">Supabase</a> and <a href="https://sendinblue.com">Sendinblue</a>.</body></html>',
    }});
```
Afterwards I got an error for updating the messages table: `'new row violates row-level security policy for table'` but I solved that for now by disabling RLS. I suppose it doesn't take much to implement the right code and enable RLS again.

**Comment by burggraf** [comment]
Great that you got it working.  As far as RLS policies go, if you insert data (or update data) by default the Supabase API does a select afterwards to get the result, but you can disable that by using the` { returning: 'minimal' } `parameter.  See https://supabase.com/docs/reference/javascript/insert#notes
