### ISSUE TITLE
email sending without any third party email providers

### ISSUE THREAD

**Issue by RekGRpth** [burggraf/supabase-mailer#4]
I setup email sending without any third party email providers!

But it requires 

- https://github.com/RekGRpth/pg_curl to send email 
and 
- https://github.com/RekGRpth/pg_task to run sql asynchronously 
and 
- https://github.com/RekGRpth/smtp.docker as own email provider

If You are interested in it, let me know.

**Comment by burggraf** [comment]
Are you kidding?  Of course I'm interested in this!  May I see it?

**Comment by RekGRpth** [comment]
Ok, I will prepare docker compose file with all things...

**Comment by burggraf** [comment]
Awesome!  Hey, did your pg extension for wkhtmltopdf ever work out?

**Comment by RekGRpth** [comment]
> did your pg extension for wkhtmltopdf ever work out?

For html to pdf I use lighter [htmldoc](https://github.com/RekGRpth/htmldoc) library now. See [postgres](https://github.com/RekGRpth/pg_htmldoc), [nginx](https://github.com/RekGRpth/ngx_http_htmldoc_module) and [python](https://github.com/RekGRpth/pyhtmldoc) bindings.

**Comment by RekGRpth** [comment]
> Ok, I will prepare docker compose file with all things...

I made it! See https://github.com/RekGRpth/pg_smtp

**Comment by RekGRpth** [comment]
> Awesome! Hey, did your pg extension for wkhtmltopdf ever work out?

I update and test it, enjoy https://github.com/RekGRpth/pg_wkhtmltopdf
