### ISSUE TITLE
SQL Error [42501]: ERROR: must be member of role "supabase_admin"

### ISSUE THREAD

**Issue by magick93** [burggraf/supabase-mailer#5]
Hello

I'm getting the this error - `SQL Error [42501]: ERROR: must be member of role "supabase_admin"`

when trying to execute this command - `ALTER TABLE public.messages OWNER TO supabase_admin;`

Are you able to help?

**Comment by burggraf** [comment]
Yes, `supabase_admin` is the default user when you're using the Supabase dashboard.  If you're not using Supabase to set all this up, you're probably running under the `postgres` user so you can replace `supabase_admin` with `postgres` here.

**Comment by magick93** [comment]
Perfect, thanks @burggraf 

Yes, I was running this locally using `postgres` then switched to the supabase dashboard and it worked there.
