### ISSUE TITLE
send_email_message returning null

### ISSUE THREAD

**Issue by biruk-tesfaye** [burggraf/supabase-mailer#7]
After following the setup from here [Mailgun](https://github.com/burggraf/supabase-mailer/blob/main/Mail_Providers/Mailgun.md).

```
select send_email_message('{
  "sender": "test@domain.com",
  "recipient": "my-email@domain.com",
  "subject": "This is a test message from my Supabase app!",
  "text_body":"Test text body",
  "html_body": "<html><body>This message was sent from <a href=\"https://postgresql.org\">PostgreSQL</a> using <a href=\"https://supabase.io\">Supabase</a> and <a href=\"https://mailgun.com\">Mailgun</a>.</body></html>"
}');
```

I get `null` as a returned value. I checked the database table `messages` and saw that the record is being inserted but I'm not receiving the email.
Any ideas on how to debug this would be greatly appreciated.

**Comment by burggraf** [comment]
Check your `public.messages` table to see if it's creating a message.  Check your logs at `Mailgun` to see if it's receiving a message or it's rejecting it for some reason.
