### ISSUE TITLE
send_email_message returns error if sending worked but messages table does not exist

### ISSUE THREAD

**Issue by christianfl** [burggraf/supabase-mailer#8]
Hey! Thanks for this, you can't believe how much time this is saving me. And it works really nice.

However I observed the following:

Setting up supabase-mailer for mailerSend without the messages table and then sending a test message results in `error sending message with mailjet: 202`. The mail was sent correctly and the 202 indicates that.

The error can be found in the `send_email_mailersend` function:

```
 IF (SELECT to_regclass('public.messages')) IS NOT NULL AND 
            retval::text = '202' THEN 
          UPDATE public.messages SET status = 'queued' WHERE id = (message->>'messageid')::UUID;
        ELSE
          RAISE 'error sending message with mailjet: %',retval;
        END IF;
```

1. It should be 'mailerSend' instead of 'mailjet'. Copy-paste error, right? :stuck_out_tongue: 
2. The if statement checks wether the table exists and no error was returned... This leads to showing error if there is none but the table does not exist

Hope this helps.

Best wishes,
Christian

**Comment by burggraf** [comment]
Thanks, I've fixed the error message as you mentioned.
